// <auto-generated />
namespace Project_Todo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EditedStudentTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditedStudentTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202303101053182_EditedStudentTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
